# Generated by Django 2.2.5 on 2021-02-02 02:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210201_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 2, 46, 45, 871719, tzinfo=utc)),
        ),
    ]
