# Generated by Django 2.2.5 on 2021-02-05 02:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20210204_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 2, 29, 50, 521905, tzinfo=utc)),
        ),
    ]
